#!/bin/bash
g++ -o evaluate evaluate.cpp;
echo "evaluate compilation completed";
g++ -o ./execs/traditional traditional.cpp;
echo "traditional compilation completed";
g++ -o ./execs/vertexMatch vertexMatch.cpp;
echo "vertexMatch compilation completed";
g++ -o ./execs/edgeMatch edgeMatch.cpp
echo "edgeMatch compilation completed"
./evaluate
